[project]
name = "air-quality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "csv",
    "geopandas>=1.0.1",
    "pyproj",
    "shapely",
]
